GET  http://localhost:8000/api/v1/staffs

###

GET http://localhost:8000/api/v1/staffs/1

###

POST http://localhost:8000/api/v1/staffs
Content-Type: application/json

{
  "first_name": "John Doe 1",
  "last_name": "Doe1",
  "email": "john@doe1.com",
  "password": "123456",
  "active": true
  
}

###

PUT http://localhost:8000/api/v1/staffs/1
Content-Type: application/json

{
  "name": "staff1-updated",
  "price": 400
}

###
DELETE http://localhost:8000/api/v1/staffs/67bfeba00e0ba9d4b210b584